# 40_season_ordination
# Sean Kinard
# 2023-08-28
#------------------------------------------------------------------------------
# setup
#------------------------------------------------------------------------------
source('exploration/toolkit.R')
library(BiodiversityR)

d_density <- read_csv("data/06_fill_data/fish_density_fill.csv")
#d_biomass <- read_csv("data/06_fill_data/fish_biomass.csv")
d_bio_categories <- read_csv("data/02_clean_data/fish_biological_scales_of_comparison.csv")
d_ste <- read_csv("exploration/output/environment_shortterm_with_ln.csv") %>%
  mutate(lf_days = exp(ln_lf_days),
         hf_days = exp(ln_flood_total_days),
         wk4_max = ln_wk4_max_to_annual_med)

RDA_evars <- c("ln_q_med", "ln_q_rsd", "lf_days", "hf_days", "wk4_max",
               "annualrain", "sqrt_rain", "temperature",
               "width", "depth_mx",
               "conductivity", "d_oxygen", "ln_nitrate", "sqrt_phosphate",
               "gravel", "silt", "total_algae" )

d_both <- left_join(d_density, d_ste) %>% add_season()
#------------------------------------------------------------------------------
# Pre-Processing Data
#------------------------------------------------------------------------------
prepare_season_predictor <- function(xdata) {
  d_both <- xdata

# fill missing predictors with linear interpolation
d_ste_fill <- d_both %>%
  rowwise() %>%
  mutate(total_algae = sum(sqrt_green_algae^2, 
                           sqrt_diatoms^2, 
                           sqrt_phosphate^2)) %>%
  select(site_code, collection_period, any_of(RDA_evars)) %>%
  unique() %>%
  as_tsibble(key=site_code,
             index=collection_period) %>%  
  na_ma(weighting="linear") %>%
  ungroup() %>%
  as_tibble() %>%
  pivot_longer(cols=-any_of(c('site_code', 'collection_period')),
               names_to='xname',
               values_to = 'x') %>%
  group_by(site_code, collection_period, xname) %>%
  dplyr::summarize(x=mean(x ,na.rm=T)) %>%
  pivot_wider(names_from=xname, values_from = x) %>%
  ungroup()

# RDA preparation: Environment
d_predictors <- d_ste_fill %>%
  unite('UID', site_code, collection_period, sep='_') %>%
  column_to_rownames("UID") }

prepare_season_spe <- function(xdata) {
  d_both <- xdata
  
  # RDA Preparation: Species
  d_spe <- d_both %>%
    unite('UID', site_code, collection_period, sep='_') %>%
    #left_join(select(d_bio_categories, lowest_taxon, total_occurances)) %>%
    #filter(total_occurances >= 10) %>%
    select(density, lowest_taxon, UID) %>%
    mutate(density = ceiling(density*1000)) %>% # transform to pseudo-abundance
    pivot_wider(names_from=lowest_taxon,
                values_from=density, 
                values_fill = 0) %>%
    column_to_rownames(var="UID") }
# ------------------------------------------------------------------------------
# RDA Calculations
#------------------------------------------------------------------------------
# function runs RDA and creates a list of data frames for plots and tables
my_rda <- function(d_env, d_spec) {
  
  # step 1: The ordiplot object is obtained from the result of via function rda. The ordination is done with a community data set that is transformed by the Hellinger method.
  # script generated by the BiodiversityR GUI from the constannualrained ordination menu
  fish_hell <- disttransform(d_spec, method='hellinger')
  Ord_model <- rda(fish_hell ~ . ,data=d_env, scaling="species")
  # This can be plotted via ordiplot
  plot2 <- ordiplot(Ord_model, choices=c(1,2))
  #------------------------------------------------------------------------------
  # Step 2 : To plot data via ggplot2
  # Extract information on the locations of sites (circles in the ordiplot)
  sites_long <- sites.long(plot2, env.data=d_env) %>%
    mutate(site_code = substr(rownames(d_env), 1,2),
           collection_period = substr(rownames(d_env), 4,13),
           collection_period = ymd(collection_period),
           cd = collection_period) %>%
    separate(cd, into=c('year', 'month', 'day'), sep='-')
  # Extract species info
  species_long <- species.long(plot2) %>%
    as_tibble() %>%
    mutate(labels = str_replace_all(labels, '\\..', '.'))
  # Information on the labeling of the axes is obtained with function axis.long. This information is extracted from the ordination model and not the ordiplot, hence it is important to select the same axes via argument 'choices'. The extracted information includes information on the percentage of explained variation. Be advised to cross-check with the summary of the redundancy analysis, where information on proportion explained is given.
  axis_long <- axis.long(Ord_model, choices=c(1, 2))
  #------------------------------------------------------------------------------
  # fit species vectors
  spp_fit <- envfit(plot2, env=fish_hell)
  df_spp_fit <- data.frame(r=spp_fit$vectors$r, p=spp_fit$vectors$pvals)
  spec_vector_long <- species.long(plot2, spec.data=df_spp_fit)
  RDA_sv <- spec_vector_long[spec_vector_long$p < 0.05, ] %>%
    as_tibble() %>% mutate(labels = str_replace_all(labels, '\\..', '.'))
  
  # fit environmental vectors
  vectors.envfit <- envfit(plot2, env= d_env)
  vectors.long2 <- filter(vectorfit.long(vectors.envfit), p < 0.05)
  RDA_ev <- vectors.long2[vectors.long2$p <= 0.05, ]
  #------------------------------------------------------------------------------
  # Table
  RDA_table <- species_long %>%
    dplyr::rename(vector = labels) %>%
    full_join(vectors.long2) %>% 
    filter(p < 0.05) %>%
    mutate(r = round(r, 3),
           p = round(p, 3),
           axis1 = round(axis1, 3),
           axis2 = round(axis2, 3)) %>%
    select(vector, r, p, axis1, axis2) %>%
    dplyr::rename('p-value'=p, 'Axis-1'=axis1, 'Axis-2'=axis2, Vector=vector)
  
  # ---------------------------------------------------------------------------
  # Format time variables
  sites_long <- sites_long %>%
    mutate(year=year(collection_period),
           month=month(collection_period),
           day=day(collection_period),
           nday=yday(collection_period),
           qtr = quarter(collection_period),
           year_week = yearweek(collection_period),
           year_month = yearmonth(collection_period)) %>%
    mutate(days_to_hh = 
             as.numeric(as_date(collection_period) - ymd('2017-08-27')) ) %>%
    mutate(weeks_to_hh = ceiling(days_to_hh/7),
           months_to_hh = round(days_to_hh/30, 0)) %>%
    mutate(site_week_label = paste(site_code, weeks_to_hh, sep="-"))
  
  # -----------------------------------------------------------------------
  # Calculate all-time centroid for each site
  mycent_alltime <-  sites_long %>%
    add_rain() %>%
    group_by(annualrain) %>%
    dplyr::summarize(axis1_mu = mean(axis1),
                     axis2_mu = mean(axis2),
                     axis1_upr = quantile(axis1, probs=.9),
                     axis1_lwr = quantile(axis1, probs=.1),
                     axis2_upr = quantile(axis2, probs=.9),
                     axis2_lwr = quantile(axis2, probs=.1))
  
  labs_alltime <- mycent_alltime %>%
    select(annualrain, axis1_mu, axis2_mu) %>%
    mutate(annualrain_label = paste(round(annualrain, 0), sep=' ')) %>%
    unique()
  # -----------------------------------------------------------------------
  # centroid distance
  centroid_distance <- sites_long %>%
    add_rain() %>%
    as_tibble() %>%
    select(site_code, annualrain, collection_period, axis1, axis2) %>%
    left_join( mycent_alltime %>% select(annualrain, axis1_mu, axis2_mu) ) %>%
    mutate(dif_x1 = axis1-axis1_mu,
           dif_x2 = axis2-axis2_mu,
           centroid_dist = sqrt(dif_x1^2 + dif_x2^2)) %>%
    select(site_code, collection_period, centroid_dist)
  # -----------------------------------------------------------------------
  RDA_out <- list(axis_long = axis_long,
                  sites_long = sites_long,
                  species_long = species_long,
                  RDA_ev = RDA_ev,
                  RDA_sv = RDA_sv,
                  RDA_table = RDA_table,
                  mycent_alltime = mycent_alltime,
                  labs_alltime = labs_alltime,
                  centroid_distance = centroid_distance)
  
  return(RDA_out) 
}

#------------------------------------------------------------------------------
# RDA environment plot function
#------------------------------------------------------------------------------
RDA_env <- function(rda_out) {
  # -----------------------------------------------------------------------
  # Index items from rda_output
  axis_long <- rda_out[[1]] %>% as_tibble()
  sites_long <- rda_out[[2]] %>% as_tibble() %>% fix_site_order() %>% 
    add_rain() %>% mutate(annualrain=round(annualrain,0)%>%as.factor())
  species_long <- rda_out[[3]] %>% as_tibble()
  RDA_ev <- rda_out[[4]] %>% as_tibble()
  RDA_sv <- rda_out[[5]] %>% as_tibble()
  mycent_alltime <- rda_out[[7]] %>% as_tibble()
  labs_alltime <- rda_out[[8]] %>% as_tibble()
  
  # ---------------------------------------------------------------------------
  # environmental Plot
  ggplot() +
    geom_convexhull(data=sites_long, aes(x=axis1, y=axis2, fill=annualrain),
                 alpha=.1, show.legend=F) +
    geom_convexhull(data=sites_long, aes(x=axis1, y=axis2, color=annualrain),
                    fill=NA, show.legend=F) +
    geom_point(data=sites_long, aes(x=axis1, y=axis2,fill=annualrain),
               shape=21, alpha=.8, size=2) +
  geom_segment(data=RDA_ev,
               aes(x=0, y=0, xend=(3*r)^2*axis1, yend=(3*r)^2*axis2),
               colour="black", linewidth=.5, 
               arrow=arrow(length=unit(0.1, "inches"),
                           type='open')) +
    # geom_label(aes(label=annualrain_label,
    #                x=axis1_mu, y=axis2_mu, fill = annualrain),
    #            data= labs_alltime, show.legend=T, color ='black' ) +
    #geom_point(data=species_long,
    #aes(x=axis1, y=axis2), 
    #color = 'white', fill='black', shape = 24, size = 2) +
    geom_text_repel(
      data=RDA_ev,
      aes(x=(3*r)^2*axis1, y=(3*r)^2*axis2, label=vector),
      color="black", box.padding = .9,
      max.overlaps = 15) +
    xlab(axis_long[1, "label"]) +
    ylab(axis_long[2, "label"]) +
    scale_x_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
    scale_y_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
    scale_fill_manual('Rainfall (cm/yr)', values = my_colors , 
                      guide = guide_legend(override.aes = list(size=4))) +
    scale_color_manual('Rainfall (cm/yr)', values=my_colors) +
    coord_fixed(ratio=1, xlim=c(-1.2,1.2), ylim=c(-1.2,1.2)) +
    theme(legend.position='bottom') +
    theme_bw(base_size = 12)
}
#------------------------------------------------------------------------------
# RDA Site Ellipse plot function
#------------------------------------------------------------------------------
# With an ordination via redundancy analysis, the positions of species should be interpreted as arrows. It is straightforward to show the positions of the species as arrows. However, with a large number of species, it is better to reduce the number to those that explain more of the variation among the sites. This information is obtained with the envfit function of vegan.

RDA_spe <- function(rda_out) {
  # -----------------------------------------------------------------------
  # Index items from rda_output
  axis_long <- rda_out[[1]] %>% as_tibble()
  sites_long <- rda_out[[2]] %>% as_tibble() %>% fix_site_order() %>% add_rain()
  species_long <- rda_out[[3]] %>% as_tibble()
  RDA_ev <- rda_out[[4]] %>% as_tibble()
  RDA_sv <- rda_out[[5]] %>% as_tibble()
  mycent_alltime <- rda_out[[7]] %>% as_tibble()
  labs_alltime <- rda_out[[8]] %>% as_tibble()
  
  # -----------------------------------------------------------------------
  # Species Plot
  ggplot() +
    # stat_ellipse(data = sites_long,
    #              aes(x=axis1, y=axis2, fill = as.factor(annualrain)),
    #              geom='polygon', alpha=.2, level = 0.9,show.legend = F) +
    # stat_ellipse(data = sites_long,
    #              aes(x=axis1, y=axis2, color = as.factor(annualrain)),
    #              alpha=.7, level = 0.9, show.legend = F) +
    #geom_rect(aes(ymin=axis2_lwr, ymax=axis2_upr,
    #              xmin=axis1_lwr, xmax=axis1_upr,
    #              fill=annualrain),
    #          data= mycent_alltime, 
    #          color=NA, alpha = .25) +
  geom_point(data=species_long,
             aes(x=axis1, y=axis2), 
             color = 'black', fill='white', shape = 24, size = 2) +
    geom_label_repel(data=RDA_sv,
                     aes(x=axis1, y=axis2, label=labels),
                     colour="black", fill = 'white', box.padding = .9,
                     max.overlaps = 25) +
    geom_label(aes(label=annualrain_label,
                   x=axis1_mu, y=axis2_mu, fill = as.factor(annualrain)),
               data= labs_alltime, show.legend=T, color ='black' ) +
    xlab(axis_long[1, "label"]) +
    ylab(axis_long[2, "label"]) +
    scale_x_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
    scale_y_continuous(sec.axis = dup_axis(labels=NULL, name=NULL)) +
    scale_fill_manual(values = my_colors) +
    scale_color_manual(values=my_colors) +
    #paletteer::scale_fill_paletteer_c("grDevices::Zissou 1", direction=-1) +
    #paletteer::scale_color_paletteer_c("grDevices::Zissou 1", direction =-1) +
    coord_fixed(ratio=1) +
    theme_bw(base_size = 12) +
    theme(legend.position = 'none') 
}

#------------------------------------------------------------------------------
# RDA season
#------------------------------------------------------------------------------
visualize_RDA_season <- function(rda_out) {
  
  # -----------------------------------------------------------------------
  # Index items from rda_output
  axis_long <- rda_out[[1]] %>% as_tibble()
  sites_long <- rda_out[[2]] %>% as_tibble()
  species_long <- rda_out[[3]] %>% as_tibble()
  RDA_ev <- rda_out[[4]] %>% as_tibble()
  RDA_sv <- rda_out[[5]] %>% as_tibble()
  mycent_alltime <- rda_out[[7]] %>% as_tibble()
  labs_alltime <- rda_out[[8]] %>% as_tibble()
  
  # ---------------------------------------------------------------------------
  # plot
  sites_long %>%
    add_rain() %>%
    add_season() %>%
    mutate(annualrain=round(annualrain,0)%>%as.factor()) %>%
    ggplot() +
    geom_point(aes(x = axis1, y = axis2, fill = season), 
               shape = 21, size=3) +
    scale_fill_manual(values = c('blue', 'orange', 'red', 'skyblue')) +
    theme_bw(base_size = 12) +
    xlab(axis_long[1, "label"]) +
    ylab(axis_long[2, "label"]) +
    coord_fixed(ratio=1)
}

#------------------------------------------------------------------------------
rda_all <- d_both %>% my_rda()

rda_winter <- my_rda(
  d_env = d_both%>%filter(season=='Winter')%>%prepare_season_predictor(),
  d_spec = d_both%>%filter(season=='Winter')%>%prepare_season_spe())

rda_spring <- my_rda(
  d_env = d_both%>%filter(season=='Spring')%>%prepare_season_predictor(),
  d_spec = d_both%>%filter(season=='Spring')%>%prepare_season_spe())

rda_summer <- my_rda(
  d_env = d_both%>%filter(season=='Summer')%>%prepare_season_predictor(),
  d_spec = d_both%>%filter(season=='Summer')%>%prepare_season_spe())

rda_fall <- my_rda(
  d_env = d_both%>%filter(season=='Fall')%>%prepare_season_predictor(),
  d_spec = d_both%>%filter(season=='Fall')%>%prepare_season_spe())

plot_rda_env_winter <- rda_winter %>% RDA_env() + ggtitle('Winter')
plot_rda_env_spring <- rda_spring %>% RDA_env() + ggtitle('Spring')
plot_rda_env_summer <- rda_summer %>% RDA_env() + ggtitle('Summer') + theme(legend.position='none')
plot_rda_env_fall <- rda_fall %>% RDA_env() + ggtitle('Fall')

plot_env_multi_season <- plot_rda_env_winter + plot_rda_env_spring + plot_rda_env_summer +
  plot_rda_env_fall + plot_layout(guides='collect')

# #------------------------------------------------------------------------------
# # Export tables
# #------------------------------------------------------------------------------
# rda_extract <- function(df, item) {
#   
#   extract_axis <- df$axis_long %>% as_tibble() %>%
#     mutate(x = label) %>%
#     separate(x, into=c('xxx1', 'xxx2'), sep=' ') %>%
#     mutate(variation_explained = gsub("[(%)]", "", xxx2) %>% as.numeric()) %>%
#     select(-contains('xxx'))
#   
#   extract_site <- df$sites_long %>%
#     as_tibble() %>%
#     select(site_code, collection_period, axis1, axis2) %>%
#     mutate(collection_period = as_date(collection_period)) %>%
#     left_join(rda_all$centroid_distance %>%
#                 as_tibble() )
#   
#   extract_vector <- df$RDA_table %>%
#     rename(p = `p-value`,
#            axis1 = `Axis-1`,
#            axis2 = `Axis-2`) %>%
#     mutate(type='physical') %>%
#     full_join(rda_all$RDA_sv %>% rename(Vector = labels) %>%
#                 mutate(type='biological'))
#   
#   if (item == 'axis') { return(extract_axis)}
#   else { if (item == 'site') {return(extract_site)}
#     else {return(extract_vector)}}
# }
# 
# rda_all_extract_axis <- rda_extract(rda_all, item = 'axis')
# rda_all_extract_site <- rda_extract(rda_all, item = 'site')
# rda_all_extract_vector <- rda_extract(rda_all, item = 'vector')
# 
# rda_1718_extract_axis <- rda_extract(rda_1718, item = 'axis')
# rda_1718_extract_site <- rda_extract(rda_1718, item = 'site')
# rda_1718_extract_vector <- rda_extract(rda_1718, item = 'vector')
# 
# rda_1920_extract_axis <- rda_extract(rda_1920, item = 'axis')
# rda_1920_extract_site <- rda_extract(rda_1920, item = 'site')
# rda_1920_extract_vector <- rda_extract(rda_1920, item = 'vector')
# 
# my_objects <- ls()
# my_csv_names <- my_objects[str_detect(my_objects, '_extract_')]
# 
# my_tables <- list(
#   rda_1718_extract_axis, rda_1718_extract_site, rda_1718_extract_vector,
#   rda_1920_extract_axis, rda_1920_extract_site, rda_1920_extract_vector,
#   rda_all_extract_axis, rda_all_extract_site, rda_all_extract_vector)
# 
# names(my_tables) <- my_csv_names
# 
# for (i in 1:length(my_tables)) {
#   my_place <- paste('exploration/output/', names(my_tables[i]), ".csv", sep='')
#   my_object <- my_tables[[i]]
#   write_csv(my_object, my_place) }

# #------------------------------------------------------------------------------
# # Export figures
# #------------------------------------------------------------------------------
# my_figure_names <- my_objects[str_detect(my_objects, '_plot')]
# 
# my_figures <- list(
#   rda_1718_env_plot, rda_1718_hh_plot, rda_1718_spe_plot, rda_1718_time_1_plot,
#   rda_1718_time_2_plot, rda_1920_env_plot, rda_1920_hh_plot, rda_1920_spe_plot,
#   rda_1920_time_3_plot, rda_all_env_plot, rda_all_hh_plot, rda_all_spe_plot,
#   rda_all_time_1_plot, rda_all_time_2_plot, rda_all_time_3_plot,
#   rda_all_time_4_plot)
# 
# names(my_figures) <- my_figure_names
# 
# for (i in 1:length(my_figures)) {
#   my_place <- paste('exploration/visualization/', names(my_figures[i]), ".png", sep='')
#   my_object <- my_figures[[i]]
#   ggsave(my_place,
#          plot = my_object,
#          width = 10,
#          height = 10,
#          units = c("in")) }

#------------------------------------------------------------------------------
# End Ordination